### ISSUE TITLE
Dotnet toolify!

### ISSUE THREAD

**Issue by praeclarum** [praeclarum/Fom#2]
- [x] Turn into console app
- [ ] Make nuget package
- [ ] Make NuGet a tool thing

**Comment by AlexHedley** [comment]
You could use the following GitHub Action to publish to NuGet

Create a new SECRET in the Settings

Call it `NUGET_API_KEY` and then generate a key as usual.

Update `PROJECT_FILE_PATH`

```yml
name: Publish to NuGet

on:
  push:
    branches:
      - master # Your default release branch

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      
      - name: Publish
        uses: rohith/publish-nuget@v2
        #uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: src/NuGetTestCore/NuGetTestCore.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
```
